### ISSUE TITLE
Re-enable/Implement GitHub pages deploy flow

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-csd#2]
We're missing some documentation on how to deploy on GitHub pages (maybe add to an INSTRUCTIONS.adoc file in the templates?) (https://github.com/metanorma/metanorma-document-gh-pages/)

Right now the user has to do the following after cloning the document template:

1. Push the document template to a GitHub repo
2. use `ssh-keygen` to generate a key-pair which will be used as the "deploy key" (filename: `deploy_key`)
3. At GitHub, upload the public key of the deploy key and authorize "write access".
4. Enable Travis for this repository.
5. Use Travis command tools to encrypt this deploy key into `deploy_key.enc`
6. Add `deploy_key.enc` to the repo and push.

During deployment:

1. The `make deploy_key` task is used to decrypt the `deploy_key.enc` into `deploy_key`. (This step is not integrated into Travis deploy!! (TODO))
2. `.travis.yml` file includes a directive to push compiled documents to GitHub pages.

**Comment by abunashir** [comment]
@ronaldtse: This seems to be assigned to me for more than over a year, is It still relevant? Is there anyone else who can take this over?

**Comment by ronaldtse** [comment]
Thanks for the ping @abunashir , @CAMOBAP can handle this (and the instructions are already outdated...).

**Comment by ronaldtse** [comment]
@CAMOBAP please help do the deploy of the mn-template-* repos (the Travis instructions are clearly outdated :wink:)

**Comment by CAMOBAP** [comment]
- https://github.com/metanorma/metanorma-cli/ - `templates/base` outdated - here is PR https://github.com/metanorma/metanorma-document-gh-pages/pull/6
 - https://github.com/metanorma/metanorma-cli/pull/168

One important open question asked in https://github.com/metanorma/metanorma-cli/pull/168

**Comment by abunashir** [comment]
Just posted a comment on the PR - https://github.com/metanorma/metanorma-cli/pull/168#issuecomment-669948944

**Comment by ronaldtse** [comment]
@CAMOBAP is this ready to be closed? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse https://github.com/metanorma/metanorma-document-gh-pages/pull/6/files this one need to be reviewed & merged first

**Comment by ronaldtse** [comment]
@CAMOBAP that is merged now. What about this?

**Comment by CAMOBAP** [comment]
@ronaldtse  I think now we are ready to go

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
