### ISSUE TITLE
Implement `metanorma new` for a collection (mini-site)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-csd#3]
https://github.com/CalConnect/csd-admin-documents is an example of a mini-site for a collection of Metanorma documents.

Within this repository, it contains a folder called `collection/` that provides a basic structure of a Metanorma collection.

For example, this could be fetched by calling `metanorma collection new my-coll` and the `my-coll/` directory will be populated.

**Comment by ronaldtse** [comment]
This relates to metanorma/metanorma-cli#180. Once that is implemented, do this.

**Comment by abunashir** [comment]
Hey @ronaldtse, I am not sure if I understand correctly, but the site generation is already done by the site interface, right? What exactly do we need here, would you mind explaining it a bit more?

**Comment by ronaldtse** [comment]
@abunashir we just need to actually make a PR to replace the Makefile and update GHA. Could you help do that? Thanks!

**Comment by ronaldtse** [comment]
We may have to tweak the HTML template design somehow...?

**Comment by abunashir** [comment]
@ronaldtse: What type of tweak we are talking about here? Could you please add some context?
> We may have to tweak the HTML template design somehow...?

**Comment by ronaldtse** [comment]
@abunashir I mean that the current Metanorma site generation uses a fixed type of template with a blue background. Different organizations may want to have their own mini-site HTML template and style (CSS). It would be best if we can have the site-generation functionality "templatized" so that each flavor (e.g. CalConnect) can tailor the HTML/CSS to their own needs. I wonder those site-generation templates should live inside the flavor gem (e.g. metanorma-cc) or separate. Probably should live inside?

**Comment by abunashir** [comment]
Ah okay, the site interface is actually delegating the HTML conversion part to Relaton CLI, and if I understand correctly then the HTML design is coming from here - https://github.com/relaton/relaton-cli/tree/master/templates, so ideally we would need to change the relaton CLI templates to be modular, I just had a quick look there and it seems to be quite coupled with some internal variables, but I would leave that up to you and Andrei.

Once we have that in place, then I think we can take that as an option from the flavor gem and pass it to the relaton.

//cc: @ronaldtse, @andrew2net

**Comment by andrew2net** [comment]
@abunashir `relaton-cli`'s `xml2html` and `yaml2html` commands have `stylesheet` and `html-template-dir` options. https://github.com/relaton/relaton-cli#relaton-xml2html
These options allow using custom templates.

**Comment by abunashir** [comment]
@andrew2net: ah superb! my bad, I must have overlooked it. In that case I think it should be easy to do, all we will need to do is to add some additional options with the `site generator` and pass it down to the relaton interface.

@ronaldtse: Considering these scenario, if we decide to go with templatization then I think it might be easier to keep the custom template with each flavor and allow them to pass it as an option or add it through the `metanorma.yml` file. Keeping it closer to each repo should also give the site maintainer more control over their own design/template.

**Comment by ronaldtse** [comment]
@abunashir In this case let's go with:

1. Custom template specified by command caller
2. Pre-defined templates specified by metanorma flavor gems

e.g.
```yaml
template:
  nist: nist-template-name
```

or
```yaml
template:
  custom: index-file-template.html
```

?
